server:
  port: 10010
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:10086/eureka
zuul:
  prefix: /api
  routes:
    user-service: /user/**
  ignored-services:
    - user-consumer
