server:
  port: 10010
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:10086/eureka
zuul:
  prefix: /api
  routes:
    user-service: /user/**
  ignored-services:
    - user-consumer
  retryable: true   # 开启重试
# AbstractRibbonCommand
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 100
  OkToRetryOnAllOperations: true
# HystrixCommandProperties
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000    # 设置hystrix的超时时间